# Generated by Django 3.0.7 on 2020-07-09 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200706_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reviews.Category'),
        ),
    ]
