# Generated by Django 3.0.7 on 2020-07-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200709_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='downs',
            field=models.IntegerField(default=0, verbose_name='down rating count'),
        ),
        migrations.AddField(
            model_name='review',
            name='ups',
            field=models.IntegerField(default=0, verbose_name='up rating count'),
        ),
    ]
