# Generated by Django 3.0.7 on 2020-07-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200716_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hotscore',
            field=models.IntegerField(default=0, verbose_name='hot rating'),
        ),
    ]
