# Generated by Django 3.0.7 on 2020-07-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_hotscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=0, verbose_name='rating count'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hotscore',
            field=models.FloatField(default=0, verbose_name='hot rating'),
        ),
    ]
