# Generated by Django 3.0.7 on 2020-09-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20200730_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-hotscore']},
        ),
        migrations.RemoveField(
            model_name='review',
            name='score',
        ),
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='reviews.Category'),
        ),
    ]
