# Generated by Django 3.0.7 on 2020-09-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20200905_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='downs',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ups',
        ),
    ]
